### ISSUE TITLE
Can't connect to database. What is the pgadmin user password?

### ISSUE THREAD

**Issue by glennrice** [YunoHost-Apps/pgadmin_ynh#29]
I have successfully installed pgadmin4 on YunoHost.

The admin user logs in OK.

But when I go to 

![image](https://github.com/YunoHost-Apps/pgadmin_ynh/assets/35488359/06fee143-7d8c-4374-9c19-3362a912749e)

and click "YunoHost Server", I get the following error:

![image](https://github.com/YunoHost-Apps/pgadmin_ynh/assets/35488359/bc4adfe8-5f65-493d-8c23-4a6c2f50a8b2)

I try the password for the pgadmin4 user that I created during the app installation.

I also tried the postgres password in /etc/yunohost/psql

It won't connect. Is there another postgresql password I missed?

**Comment by ImaCrea** [comment]
Same issue here :/ Did you find the solution maybe?

**Comment by glennrice** [comment]
Nope, not yet. I gave up at the time, but I'll have to have another look...

**Comment by Josue-T** [comment]
Hello,

There need a fix on the app for this. For now the workaround is to add a new db server (instead of "yunohost server" and to add the password stored in the app settings. It's in the file `/etc/yunohost/apps/pgadmin/settings.yml` and the key should be something like `db_pwd` (don't remember exactly).

**Comment by Salamandar** [comment]
The app now provides the password at the end of the installation. You can still find `db_pwd`in the settings file.
